AWSTemplateFormatVersion: "2010-09-09"
Description: 親スタック

Resources:
  vpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://test-f-aidai.s3.ap-northeast-1.amazonaws.com/CLF-template/vpc.yaml
      Parameters:
           VPCCiderBlock: 10.0.0.0/16