AWSTemplateFormatVersion: 2010-09-09

Parameters:
  # VPC ID
  VPCId:
    Description: The ID of the VPC to be created.
    Type: AWS::EC2::VPC::Id

Resources:
#----------------------------------------
# RDSのセキュリティグループ
#----------------------------------------
  MyDataBaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: test security group
      VpcId: !Ref VPCId

  #----------------------------------------
  # インバウンドルール
  #----------------------------------------
  MySQLInboundToDB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref MyEC2SecurityGroup
      GroupId: !Ref MyDataBaseSecurityGroup

  SSHInboundToDB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref MyEC2SecurityGroup
      GroupId: !Ref MyDataBaseSecurityGroup

#----------------------------------------
# EC2のセキュリティグループ
#----------------------------------------
  MyEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: test security group
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  #----------------------------------------
  # アウトバウンドルール
  #----------------------------------------
  DataBaseOutboundfromEC2:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      DestinationSecurityGroupId: !Ref MyDataBaseSecurityGroup
      GroupId: !Ref MyEC2SecurityGroup

  SSHOutboundfromEC2:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      DestinationSecurityGroupId: !Ref MyDataBaseSecurityGroup
      GroupId: !Ref MyEC2SecurityGroup

#----------------------------------------
# VPCエンドポイント用のセキュリティグループ
#----------------------------------------
  VPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to the VPC endpoint
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: VPCEndpointSecurityGroup

Outputs:
  # データベースインスタンス用のセキュリティグループ
  DataBaseSecurityGroupId:
    Value: !Ref MyDataBaseSecurityGroup

  # webサーバーインスタンス用のセキュリティグループ
  EC2SecurityGroupId:
    Value: !Ref MyEC2SecurityGroup

  # VPCエンドポイント用のセキュリティグループ
  VPCEndpointSecurityGroupId:
    Value: !Ref VPCEndpointSecurityGroup