AWSTemplateFormatVersion: 2010-09-09

Parameters:
#-----------------------------------------
# スタック作成時に手動で入力する項目
#-----------------------------------------
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC-Id where you want to set up the SSM endpoint.

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The Subnet-Id Where you wont to set up the SSM endpoint.

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The SecurityGroup-Id Where you wont to set up the SSM endpoint.


Resources:
#-----------------------------------------
# スタックが作成するリソース
#-----------------------------------------
#-----------------------------------------
# VPCエンドポイント
# プライベートサブネットのSSM接続に必要
#-----------------------------------------
  # SSMのVPCエンドポイント
  SSMVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      SubnetIds:
        - !Ref SubnetId
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: ssm-endpoint

  # SSMMessageのVPCエンドポイント
  SSMMessageVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      SubnetIds:
        - !Ref SubnetId
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: ssmmsg-endpoint

  # EC2MessageのVPCエンドポイント
  EC2MessageVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      SubnetIds:
        - !Ref SubnetId
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: ec2msg-endpoint


Outputs:
#-----------------------------------------
# スタックの返り値を出力する部分
#-----------------------------------------
  # SSMのVPCエンドポイント
  SSMVPCEndpoint:
    Value: !Ref SSMVPCEndpoint

  # SSMMessageのVPCエンドポイント
  SSMMessageVPCEndpoint:
    Value: !Ref SSMMessageVPCEndpoint

  # EC2MessageのVPCエンドポイント
  EC2MessageVPCEndpoint:
    Value: !Ref EC2MessageVPCEndpoint